### ISSUE TITLE
Build failed: Could not resolve all files for configuration ':react-native-snackbar:classpath'.

### ISSUE THREAD

**Issue by wahabtobibello** [cooperka/react-native-snackbar#100]
Hi @cooperka,

So i tried building my react native project with react-native run-android and I got this error

![screen shot 2018-12-11 at 8 44 44 pm](https://user-images.githubusercontent.com/17463997/49825920-e472b300-fd85-11e8-9d8f-4ffbd33320a0.png)

It seems react-native-snackbar uses the gradle version 2.3.3 but this version is not available in jcenter as the urls: https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom and https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.jar return 404.

Please, do you have a solution or a walk-around to this?

**Comment by DiepEsc** [comment]
My simple solution is as following steps:
- Move react-native-snackbar out of node_modules folder. (Ex: move to new folder: modified_modules)
- Upgrade the gradle build tool version, also add google repository in react-native-snackbar/android/builde.gradle. Like this
``` gradle
buildscript {
    repositories {
	google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
    }
}
```
- Change react-native-snackbar version in package.json. Like this 
```"react-native-snackbar": "file:modified_modules/react-native-snackbar"```
- run `npm install`.

Hope the author fixes it soon.

**Comment by wahabtobibello** [comment]
Thanks a lot, @DiepEsc. I was able to get it working with your solution. I also hope it can be fixed soon.

**Comment by cooperka** [comment]
Hi @tobibello001, I'm glad a workaround helped. Gradle v2.3.3 is used by default by React Native, so I find it strange that that version isn't working for you. Are you able to link to an example app that had this problem?

**Comment by cooperka** [comment]
> Hope the author fixes it soon.

@DiepEsc please feel free to submit a PR if you want to help contribute to open-source software 😺 Thanks.

**Comment by cooperka** [comment]
Closing as stale. Please reply here if you have further issues.
