### ISSUE TITLE
index.d.ts provides wong information

### ISSUE THREAD

**Issue by wodka** [cooperka/react-native-snackbar#104]
the structure in the index.d.ts (type definitions) imply that the lib must be imported by:

`import * as Snackbar from 'react-native-snackbar';`

but instead it provides a default export that contains the mentioned functions. meaning the above statement would then require calls like `Snackbar.Snackbar.show(...)`

so the file would have to include:

```ts
interface Snackbar{
  LENGTH_SHORT: number;
  LENGTH_LONG: number;
  LENGTH_INDEFINITE: number;

  show(options: SnackBarOptions): void;
  dismiss(): void;
}

export default Snackbar;
```

**Comment by wodka** [comment]
so the file would have to include:

```ts
interface Snackbar{
  LENGTH_SHORT: number;
  LENGTH_LONG: number;
  LENGTH_INDEFINITE: number;

  show(options: SnackBarOptions): void;
  dismiss(): void;
}

export default Snackbar;
```

**Comment by cooperka** [comment]
Thanks @wodka, do you mind submitting a quick PR to fix this?

**Comment by wodka** [comment]
@cooperka just created the pull request
