### ISSUE TITLE
Undefined is not an object - RNSbackbar.LENGTH_LONG

### ISSUE THREAD

**Issue by kresogalic8** [cooperka/react-native-snackbar#108]
Hey guys I got this error after yarn add, and importing. 

![56595504_2097050987251719_8939324542237540352_n](https://user-images.githubusercontent.com/7289406/55755361-16073c80-5a4f-11e9-9205-4e47759fc49d.jpg)

**Comment by cooperka** [comment]
You can find help on the [README here](https://github.com/cooperka/react-native-snackbar#undefined-import), merging into https://github.com/cooperka/react-native-snackbar/issues/43. Hope that helps!
