### ISSUE TITLE
Snack bar is not show when modal is open in react native.

### ISSUE THREAD

**Issue by nitinAct** [cooperka/react-native-snackbar#109]
I'm using a snack bar for validation but it's using in modal of react native. it is a critical issue that while a modal is  open snack show fast and goes away

**Comment by cooperka** [comment]
Hi @nitinAct, I need more information to understand what the issue is. Can you provide a screenshot and/or steps to explain what you want to achieve?

**Comment by nitinAct** [comment]
Thanks, buddy I found the way to solve the issue

**Comment by swathi2378** [comment]
@nitinAct how did you solve the issue?

**Comment by cooperka** [comment]
@swathi2378 see #28 for some potential workarounds for similar issues.

**Comment by nitinAct** [comment]
> @nitinAct how did you solve the issue?

no but i made another static container rather than it
i still can't understand why  this happing
