### ISSUE TITLE
Snackbar ellipsizes text after 2 lines

### ISSUE THREAD

**Issue by abhilash-behera** [cooperka/react-native-snackbar#110]
Snackbar is not showing full text when text length increases more than one line. There should be option to show number of lines.
![Screenshot_2019-05-20-17-53-10-73_b24c65ed21396e6786850b6135539d98](https://user-images.githubusercontent.com/13430073/58021355-4ea73500-7b28-11e9-8953-ed782c952452.png)

**Comment by cooperka** [comment]
Thanks @abhilashfancy, I've marked this as a feature request. I'll be happy to accept a PR that provides this option.

**Comment by cooperka** [comment]
Added in https://github.com/cooperka/react-native-snackbar/pull/171
