### ISSUE TITLE
Does not work on android over Modal with ProGuard

### ISSUE THREAD

**Issue by FelipePaiva1992** [cooperka/react-native-snackbar#113]
I try to show the `Snackbar` over a Modal

If I disable the proguard, everthing works fine.
But if I enable the `Snackbar` stop work only over a Modal.

**Comment by cooperka** [comment]
Thanks @FelipePaiva1992. Possibly related to https://github.com/cooperka/react-native-snackbar/issues/28. If you find a fix for this I'd welcome a PR.

**Comment by anurag060** [comment]
Hi @FelipePaiva1992. I am also facing the same issue when the proguard is enabled. Can you please tell me the steps to fix this.

**Comment by FelipePaiva1992** [comment]
@anurag060 this issue was not be fixed by the main dev.

I recommend you to use other lib like
https://callstack.github.io/react-native-paper/snackbar.html

Because this is an old issue, more or less two year ago.

**Comment by anurag060** [comment]
Hi @cooperka..can you help me with this issue?

**Comment by cooperka** [comment]
Please refer to #28 for issues with modals. You might try using `setTimeout` to work around this issue. Thanks.

**Comment by AbdulBsit** [comment]
add `-keep class com.facebook.react.views.modal.ReactModalHostView { *; }` this in your `proguard-rules.pro` file, this will fixes the issue #212
