### ISSUE TITLE
Execution failed for task ':app:processDebugManifest'.

### ISSUE THREAD

**Issue by VadimOsovsky** [cooperka/react-native-snackbar#118]
![Screenshot 2019-07-23 at 14 21 57](https://user-images.githubusercontent.com/39897981/61708382-5caa4980-ad55-11e9-8ca3-4e2131353b41.png)

**Comment by AndersonCossul** [comment]
![Screen Shot 2019-07-29 at 14 03 20](https://user-images.githubusercontent.com/19210930/62067292-bf925980-b209-11e9-9056-117f25feff5f.png)

What version of RN are you using?

I was having the same issue when using v0.59.

**Comment by AndersonCossul** [comment]
![Screen Shot 2019-07-29 at 14 03 20](https://user-images.githubusercontent.com/19210930/62067292-bf925980-b209-11e9-9056-117f25feff5f.png)

What's your RN version?

I was having the same issue when using v0.59.

**Comment by VadimOsovsky** [comment]
@AndersonCossul I'm currently on 0.59

**Comment by cooperka** [comment]
@VadimOsovsky as noted above, please upgrade to RN v0.60 in order to use Snackbar v2.0. Thanks!
