### ISSUE TITLE
Compile issues since last update for COLOR [Android]

### ISSUE THREAD

**Issue by iRoachie** [cooperka/react-native-snackbar#12]
Android 4.4.4 - API 19 

```
Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
```

**Comment by iRoachie** [comment]
Error shows on Android 6.0 as well

**Comment by cooperka** [comment]
@iRoachie I don't seem to have any errors on my devices, does this cause any problems for you? Does the app still work?

**Comment by iRoachie** [comment]
Nope. The bug appears when building

**Comment by iRoachie** [comment]
Okay I figured out what the problem was. I'm assuming it has something do with the Android Support Library an API 23. After I changed the build.grade to api > 23, it build correctly.

My settings:
compileSdkVersion 25
buildToolsVersion "25.0.2"

Original react native settings:
compileSdkVersion 23
buildToolsVersion "23.0.1"

**Comment by Clowning** [comment]
No news?

**Comment by SrinivasanSelvam** [comment]
I have got the same error.  

How to change sdk version?
Guide me where is that option in Android stuido

**Comment by iRoachie** [comment]
It's a file `android/app/build.gradle`
