### ISSUE TITLE
Issue using along mobx

### ISSUE THREAD

**Issue by almeida-samuel** [cooperka/react-native-snackbar#123]
Hello, good evening.

@cooperka do you know something about this issue: https://github.com/mobxjs/mobx/issues/2110

Btw, my call of `Snackbar.error({ title: this.error })` is a simple wrap of the normal `.show` with some predefined parameters, like the background color.

**Comment by cooperka** [comment]
Thanks for the detailed reports @almeida-samuel. Could you create a minimal example app to reproduce this bug? That would help diagnose the problem.

By chance, are you using any modals that appear/disappear related to the error? Snackbar can sometimes get attached to the modals and not appear on screen, see #28
