### ISSUE TITLE
Unable to run my application

### ISSUE THREAD

**Issue by EdisonDevadoss** [cooperka/react-native-snackbar#130]
After I installed **react-native-snackbar** I could not run my application.
In this application, I used **react-native-navigation**.
Please help me. I attached the below error.

![Screenshot from 2019-10-22 17-57-51](https://user-images.githubusercontent.com/30063304/67285830-e7861600-f4f5-11e9-8860-25eccf6a9ecc.png)

```
Execution failed for task ':app:processDebugManifest'
Manifest merger failed
```

**Comment by cooperka** [comment]
Hi @EdisonDevadoss, this is an unusual error and likely due to a project configuration. Have you looked at the relevant location in AndroidManifest.xml:7 and tried the suggested solution?

Closing for now; please let me know if this ends up being related to Snackbar and I'm happy to re-open.
