### ISSUE TITLE
Snackbar doesn't go away when user tap in it.

### ISSUE THREAD

**Issue by bbeckk** [cooperka/react-native-snackbar#131]
How to make snackbar disppear when it is tapped?

```
Snackbar.show({
  title: 'Hello world',
  duration: Snackbar.LENGTH_SHORT,
});
```

**Comment by cooperka** [comment]
Hi @bbeckk, you can add an `action` if you want the user to be able to tap something (see readme for details). Otherwise, the snackbar can't be tapped.
