### ISSUE TITLE
Build crash in Android

### ISSUE THREAD

**Issue by manuga93** [cooperka/react-native-snackbar#14]
Hi, I've done `npm install` and `react-native link react-native-snackbar` and I get this output:

`node_modules/react-native-snackbar/android/src/main/java/com/azendoo/reactnativesnackbar/SnackbarModule.java:70: error: package android.support.design.R does not exist
            TextView snackbarText = (TextView) snackbarView.findViewById(android.support.design.R.id.snackbar_text);`

I've tried with 23 and 25 compile sdk version and it persists. What could I do?

Thanks

**Comment by cooperka** [comment]
Hi @garridev, have you tried upgrading Gradle? What version are you on? https://github.com/cooperka/react-native-snackbar#notes

**Comment by manuga93** [comment]
Yes I will. This change allow me to build apk but get this other error 
![captura de pantalla de 2017-02-01 22-23-55](https://cloud.githubusercontent.com/assets/7095548/22526922/8275ec0e-e8cd-11e6-83d1-5c2a229f9d9a.png)

**Comment by cooperka** [comment]
Hmm, it's hard to tell if that's related to this module or not. Can you try removing `react-native-snackbar` and see if that fixes the error?

Unfortunately this error message doesn't really have any details that help narrow it down! You could also try searching Google for the error message.

**Comment by manuga93** [comment]
Thank you for your answers. Yes, without `react-native-snackbar` problems are solved.

 What's your gradle wrapper version?

**Comment by cooperka** [comment]
https://github.com/facebook/react-native/issues/6035

Can you try disabling Chrome debugging, or maybe one of the other solutions suggested there?

**Comment by cooperka** [comment]
Here's the link to the example app's gradle wrapper: https://github.com/cooperka/react-native-snackbar/blob/master/example/android/gradle/wrapper/gradle-wrapper.properties

**Comment by cooperka** [comment]
@garridev any luck?

**Comment by manuga93** [comment]
yeah I just had to restart packager :) 
Thank you

**Comment by cooperka** [comment]
Haha, too easy! Good to know this was the fix.

**Comment by raphaelpinel** [comment]
I uninstalled and resinstalled react-native-snackbar and it worked. `npm uninstall react-native-snackbar` `npm i react-native-snackbar`
