### ISSUE TITLE
Margin Bottom,Left & Right is missing

### ISSUE THREAD

**Issue by noumansakhawat-dev** [cooperka/react-native-snackbar#140]
Missing margins on Bottom Left and right

**Comment by cooperka** [comment]
Closing in favor of #15, as this addresses the same need. Thank you for the PRs, I will comment on them soon!

**Comment by noumansakhawat-dev** [comment]
> Closing in favor of #15, as this addresses the same need. Thank you for the PRs, I will comment on them soon!


I created a pull request for Margin Bottom ,Left and Right
