### ISSUE TITLE
Can we have an option to re-position SnackBar ?

### ISSUE THREAD

**Issue by ausshadu** [cooperka/react-native-snackbar#150]
Hi, 
Can we have an option to re-position SnackBar, currently it is painted at the very bottom of the screen, if we can include an option to change it or add some `bottomMargin` offset value, it would be nice.

Project Settings:
RN: 0.61.5
Platform: iOS and Android

**Comment by cooperka** [comment]
Indeed! Please see #15 for discussion of positioning, along with open PR #137; that PR is blocked on feedback that needs to be addressed by the submitter. If you'd like to address my feedback and submit an updated PR for margins, feel free! Thanks.
