### ISSUE TITLE
how to increase font size of text Snackbar?

### ISSUE THREAD

**Issue by Rizwan-Ijaz** [cooperka/react-native-snackbar#152]
There are multiple properties to adjust text like textColor, fontFamily but there is no property to adjust font size of snakbar

**Comment by cooperka** [comment]
Thanks @Rizwan-Ijaz! I'm going to merge this feature request into a related one: https://github.com/cooperka/react-native-snackbar/issues/47

I am open to this change if you are interested in submitting a pull request.

**Comment by shayanfarshad** [comment]
> Thanks @Rizwan-Ijaz! I'm going to merge this feature request into a related one: #47
> 
> I am open to this change if you are interested in submitting a pull request.

i want to do it
