### ISSUE TITLE
Does not work with modals

### ISSUE THREAD

**Issue by SandroMachado** [cooperka/react-native-snackbar#16]
If I try to show a `Snackbar` in a `Modal`, the `Snackbar` will be displayed behind the modal and it will not be visible.

**Comment by ravirupareliya** [comment]
Is it resolved? or we need to go with the bug?

**Comment by cooperka** [comment]
Hi @ravirupareliya, this should have been fixed in #17. Are you still experiencing this bug?

**Comment by carloscuesta** [comment]
Can confirm that I'm still experiencing this bug when using the `Snackbar` with a `react-native` `Modal` on Android.

The render of the Snackbar goes away with modal.

**Comment by hmlund** [comment]
Hi, any updates on this? I'm having the same issue. It works with modals on ios, but not on android. I am using React Native Navigation as navigation.
