### ISSUE TITLE
Does not work from inside an async generator?

### ISSUE THREAD

**Issue by ospfranco** [cooperka/react-native-snackbar#160]
Hey, I was facing the issue when attaching to a parent that gets dismissed, so when I call the snackbar from a setTimeout everything works fine, but when I try to call it inside a async generator (redux saga in this case), it explodes:

![87920609-bda85280-ca79-11ea-9812-43d2d6dc241f](https://user-images.githubusercontent.com/1634213/87944997-6b2e5c80-caa0-11ea-9fa6-3231a336eacd.png)

I have a suspicion that this has to do with the fact that setTimeout is an API that runs on the event loop and generators are language level constructs

**Comment by cooperka** [comment]
To be clear, is this a setTimeout **within** an async generator that's not working? A working demo app would be super helpful if you're able to provide it.

**Comment by ospfranco** [comment]
Hi @cooperka, thanks for answering, I just tested this again and it seems it was a problem with the generator itself, but rather the time that the call was delayed, increasing the time gets rid of the error and allows the snack show properly, thanks!
