### ISSUE TITLE
Change snackbar position to top?

### ISSUE THREAD

**Issue by atmeshwar-classic** [cooperka/react-native-snackbar#161]
Hi @cooperka !,
First of all, thanks for the awesome library. 
I wanted to propose a change where we could pass a config parameter for changing the position of the snackbar to either top or bottom.
Do you think it is possible?
Regards,
Atmeshwar

**Comment by TheSecMaven** [comment]
trying to do this myself right now not much luck

**Comment by cooperka** [comment]
Closing as duplicate of https://github.com/cooperka/react-native-snackbar/issues/15. I welcome a PR if you'd like to try it!
