### ISSUE TITLE
Multiple action buttons in one Snackbar

### ISSUE THREAD

**Issue by bachbonglong** [cooperka/react-native-snackbar#163]
I want 2 actions in 1 snackbar ... is that possible? Like this -> 
![image](https://user-images.githubusercontent.com/42697834/90303978-3e256c00-dedd-11ea-9f3a-ab5297f1cb1a.png)

Thanks you .

**Comment by cooperka** [comment]
Hi @bachbonglong, thanks for the input. This is not currently possible, but it sounds useful. I think it may technically be against Material Design guidelines, so I would rather not support this directly in the library, but if you want to create a fork and implement the feature there, please share a link so others can use it too :)

**Comment by cooperka** [comment]
Closing the feature request, but feel free to continue the discussion here.
