### ISSUE TITLE
Inconsistency when opening new snackbar one after another.

### ISSUE THREAD

**Issue by Ajmal0197** [cooperka/react-native-snackbar#169]
I want snackbar to use two different coloured snackbar but the second one shows previous snackbar for a small time then shows actual one.
I have already used Snackbar.dismiss() on leaving screen. But still this happens.

Below is video link:
https://drive.google.com/file/d/1Cs35xSu8tDgh6LY7g7PyYQEjI14qZCMB/view?usp=drivesdk

**Comment by cooperka** [comment]
Hi @Ajmal0197, thanks for the video documentation. Could you also explain what your code is doing? I see a flash of blue that's immediately replaced by yellow. Do you want both snackbars to show at the same time (not possible) or do you expect the blue one to have been visible for longer before switching to yellow?

**Comment by Ajmal0197** [comment]
> Hi @Ajmal0197, thanks for the video documentation. Could you also explain what your code is doing? I see a flash of blue that's immediately replaced by yellow. Do you want both snackbars to show at the same time (not possible) or do you expect the blue one to have been visible for longer before switching to yellow?

Hi @cooperka ,
On first screen i want to show yellow snackbar and on second blue one. But on second screen yellow one still shows for milliseconds then comes blue. I have already cleared it on page unmount.

**Comment by cooperka** [comment]
Could you please share a working demo app on GitHub that I can test? It's hard to understand what the issue might be otherwise. Thanks!
