### ISSUE TITLE
#58 This issue is still showing for me.

### ISSUE THREAD

**Issue by ImAbhishekTomar** [cooperka/react-native-snackbar#170]
I am facing #58 this issue in my new project.. Is the marge in the new version?

**Comment by cooperka** [comment]
Hi @ImAbhishekTomar, that PR was not merged because the workaround should happen locally in your codebase. Please review my comment on that PR for advice. Thanks!

**Comment by ImAbhishekTomar** [comment]
Thanks, I will check.
