### ISSUE TITLE
Snackbar.LENGTH_INDEFINITE dismiss immediately

### ISSUE THREAD

**Issue by tarouboy** [cooperka/react-native-snackbar#178]
It works fine when I call the snackbar on component, e.g. componentDidMount;
However it will dismiss immediately if I call the snackBar in anywhere else, e.g.g redux saga
It used to be working in such cases.

**Comment by cooperka** [comment]
Hi @tarouboy, could you have a look at this issue and see if a similar workaround helps you? https://github.com/cooperka/react-native-snackbar/issues/28

Happy to re-open if this is a different issue; in that case please provide an example app so I can help test. Cheers.
