### ISSUE TITLE
[Test] Cannot read property 'LENGTH_LONG' of undefined 

### ISSUE THREAD

**Issue by vijaemanlapaz** [cooperka/react-native-snackbar#194]
I'm getting error **_Cannot read property 'LENGTH_LONG' of undefined_** when i do `yarn test`
i'm using version **2.4.0**

Environment
react-native: 0.65.2 => 0.65.2

Steps i did so far
- yarn clean
- yarn install
- npx react-native link react-native-snackbar

**Comment by viral-synoverge** [comment]
how to resolve this ? any one able to find the solution ?

**Comment by joseananio** [comment]
see this issue: https://github.com/cooperka/react-native-snackbar/issues/43. 
its on regular usage but you might find something

Also ensure your pods are installed `(RNSnackbar (2.4.0))`.

**Comment by atul898** [comment]
I am getting a similar message - "Cannot read **properties** of undefined (reading 'LENGTH_LONG')"
Functionality is all good, this issue is specific to when running tests
We are on React Native "0.67.2", using "2.4.0" of react-native-snackbar
Already went through issue #43 and tried everything.

**Comment by GewoonJaap** [comment]
> I am getting a similar message - "Cannot read **properties** of undefined (reading 'LENGTH_LONG')" Functionality is all good, this issue is specific to when running tests We are on React Native "0.67.2", using "2.4.0" of react-native-snackbar Already went through issue #43 and tried everything.

Same issue here, works fine when using the app, however once I run Jest it will fail. Already added the package to Jest `transformIgnorePatterns`, without result

**Comment by ZeeshanAhmadKhalil** [comment]
I was getting this issue, uninstalling app, closing metro server and running app again worked for me.

**Comment by aravi365** [comment]
Any working solution or fixes on this issue?

**Comment by jakequade** [comment]
If anyone is struggling with this, you can create a mock in your `jest.setup.js`:

```js
jest.mock('react-native-clipboard', () => ({
    LENGTH_SHORT: 5,
    LENGTH_LONG: 10,
    LENGTH_INDEFINITIE: -1,
    show: jest.fn(),
    dismiss: jest.fn(),
})
```

I've addressed this in a PR, here: https://github.com/cooperka/react-native-snackbar/pull/210

**Comment by cooperka** [comment]
Thank you @jakequade, hopefully that clears up the confusion. Closing this issue.
