### ISSUE TITLE
npm i react-native-snackbar fetching version "react-native-snackbar": "^2.6.2",

### ISSUE THREAD

**Issue by forever-sumit** [cooperka/react-native-snackbar#208]
I run the commandd `npm i react-native-snackbar` its add `"react-native-snackbar": "^2.6.2",` in package.json.

Reason is on github showing version `2.7.1` but on [https://www.npmjs.com/package/react-native-snackbar](https://www.npmjs.com/package/react-native-snackbar) its `2.6.2`

so can you please fix that

**Comment by cooperka** [comment]
Thank you for flagging this @forever-sumit, v2.7.2 is now the default version.
