### ISSUE TITLE
Add onDismiss callback

### ISSUE THREAD

**Issue by raynor85** [cooperka/react-native-snackbar#27]
It would be useful to be able to hook a callback when the snackbar is dismissed, both for automatic dismiss (when duration reaches its end) and when the user opens another snackbar when the current one is active

**Comment by cooperka** [comment]
Hi @raynor85, I'd certainly accept a PR for this! Out of curiosity, what do you need it for?

**Comment by iRoachie** [comment]
For example: Add Event Modal,

Enter details -> press add -> show snackbar message "Event added" -> Close modal.

Currently for the close modal i'm using a setTimeout for the time i think the snackbar would last for.


![snackbar](https://cloud.githubusercontent.com/assets/5962998/24870784/6e54881e-1de5-11e7-899a-4f0e8503517f.gif)

**Comment by cooperka** [comment]
Hmm, @iRoachie I think the standard behavior there would be to close the modal immediately and then show a snackbar to confirm it was submitted, rather than making the user wait.

Here are the official guidelines: https://material.io/guidelines/components/snackbars-toasts.html

**Comment by iRoachie** [comment]
The guidelines don't actually say anything about implementation, but i'll still take your suggestion. I still think it'd be a good thing to have. Like if you want to give the user time to read something, before navigating away.

**Comment by cooperka** [comment]
No response from @raynor85 so I will close this for now. Happy to re-open if there are good use cases for it, but I'd rather not add complexity if it's not needed.

**Comment by raynor85** [comment]
Well the use cases can be multiple. For example think about an UNDO
snackbar. You would be able to hook up an action (like a server request to
save a resource) only when the snackbar is dismissed. If you press on undo,
you just update the UI without dispatching an action.

**Comment by cooperka** [comment]
That does seem useful in theory -- but what if the user clicks the button, sees the "Action has been performed" snackbar, and immediately kills the app? Then the action will never actually have been performed, even though you told the user it was.

It seems like needing a feature like this is a code smell, and it could lead to bad practice. Anecdotally, it also doesn't appear to be supported by Google, and they tend to have good judgment about usability.

**Comment by iRoachie** [comment]
@cooperka callback for snackbars was added since api 23. http://stackoverflow.com/a/33076569/1862272

**Comment by raynor85** [comment]
Up to you man, I think it is always good to provide callbacks in general,
and give powers to developers, instead that not doing so. In this case I
needed to hook up actions for my use case and not having a callback leaded
me to use another snackbar component. PS: Google doesn't own the holy
grail, and angular is just an example of that :D

**Comment by cooperka** [comment]
@iRoachie thanks for the link! That's good to know. My knowledge seems to be outdated ;)

Again, I'm happy to merge a PR if someone makes one 🍹

**Comment by iRoachie** [comment]
lol i'm not the best android programmer, but I'll give it a go

**Comment by cooperka** [comment]
If you do, I think I'd prefer to follow the [latest API's `addCallback`](https://developer.android.com/reference/android/support/design/widget/BaseTransientBottomBar.html#addCallback(android.support.design.widget.BaseTransientBottomBar.BaseCallback<B>)) (and of course fall back for earlier SDKs).

**Comment by Noitidart** [comment]
Dang this is something i need to. I use redux-saga, and in redux-saga we need to do `yield put` which we can't do from onPress as it is not a generator. So what we do is turn it into a promise:

```
function* cancelRecordingWorker() {
    const didUndoPromise = new Promise();
    Snackbar.show({ title:'Canceled', ... onPress:()=>didUndoPromise.resolve(true) });

    const didUndo = yield didUndoPromise;
   
   if (didUndo) yield put(...);
}
```

Without the dismiss I end up hanging on a promise forever. I'm doing a work around for now with not using indefinite.
:(

**Comment by cooperka** [comment]
@Noitidart instead of `yield put`, try passing `dispatch` into your saga so you can call `dispatch` directly in `onPress`. I used this same pattern in a few of my apps and it works quite well.

Assuming you have a root saga, do something like this while configuring your redux store:

```js
const sagaMiddleware = createSagaMiddleware();
sagaMiddleware.run(() => rootSaga(store.dispatch));
```

And then pass `dispatch` from your root saga into any other saga that needs to use it.

**Comment by Noitidart** [comment]
Ooo thanks I didn't think of that!

I would need still need 2 dispatches though. One for if pressed action item. One for if dismissed. :(

**Comment by cooperka** [comment]
Generally when showing an "undo" button you should perform the regular action immediately, notify the user with the snackbar, and if they press "undo" then you reverse the action. No dismiss callback should be needed. See my comment [above](https://github.com/cooperka/react-native-snackbar/issues/27#issuecomment-293977389) for reasoning.

**Comment by Noitidart** [comment]
Ah thanks so much you really helped me learn a lot today. UI, UX and even redux-saga!! I'll do it this way then :)

**Comment by terreb** [comment]
However this issue is closed as wontfix, implementation of the dismiss callback would be helpful. In my app I send a request to the backend once the snackbar is dismissed or auto dismissed (currently using another package, but would love to switch to this one due to it being native rather just js). Unfortunately, I'm not experienced neither in native iOS nor Android development, so unable to help.
