### ISSUE TITLE
Undefined not an object (_reactNative.nativeModules.RNSnackbar,.LENGTH.LONG_

### ISSUE THREAD

**Issue by Jazz747** [cooperka/react-native-snackbar#29]
![screenshot_2017-05-08-11-56-20-544_hr aduro midway](https://cloud.githubusercontent.com/assets/12306271/25800301/ffa8f8b8-33e8-11e7-9ce7-603e47fadb97.png)

On app start, crashes a few seconds later
RN 0.42.3, linked, error appears when putting the import statement in JS

**Comment by ghost** [comment]
Same with mine too.

**Comment by cooperka** [comment]
Hmm, it works for me on that version, both iOS and Android. Have you
rebuilt and restarted your packager after linking? Try clearing all your
caches and building your app from scratch just in case.

E.g. clean absolutely everything then `react-native run-android`.

**Comment by ghost** [comment]
Ok, i would do that

**Comment by Jazz747** [comment]
The problem still persists after cleaning the project in Android studio, deleting node_modules and doing `npm install`.

I've recently upgraded to RN 0.42.3 from 0.38, getting 
`npm WARN react-native@0.42.3 requires a peer of react@~15.4.1 but none was installed.`
installed the aforementioned version of React, warning still persists but everything works. Don't know if that has anything to do with this issue.

**Comment by iRoachie** [comment]
This looks like a link error. @Jazz747 After you `npm install`, run `react-native link react-native-snackbar` then start your packager and build the app

**Comment by Jazz747** [comment]
I did, result:
`Cannot parse yarn version: 0.27
Scanning 467 folders for symlinks in /home/username/Projects/project/node_modules (2ms)`
`rnpm-install info Android module react-native-snackbar is already linked `
`rnpm-install info iOS module react-native-snackbar is already linked `

Manual install instructions would be helpful, I see the snackbar inclusion in `settings.gradle` and `app/build.gradle` but not anywhere else, not sure if it should be included in `MainApplication` file

**Comment by iRoachie** [comment]
Yes it should be in `MainApplication.java`

```java
import com.azendoo.reactnativesnackbar.SnackbarPackage;

// Then in class
 @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new SnackbarPackage(),
      );
    }
```

**Comment by Jazz747** [comment]
Yep, that fixed it :)

I've had multiple problems in the past with linking of libraries, had to do it manually, so it would be cool if there were manual installation instructions on the main page also. Cheers!

**Comment by iRoachie** [comment]
@Jazz747 Awesome! If you could send a PR with the manual steps i'm sure @cooperka wouldn't mind.

**Comment by Jazz747** [comment]
I'm somewhat unfamiliair on how to create pull requests since I'm new to Github, so I'll just make it here, in hopes that @cooperka can paste it into the description section if he wants to.

In `android/settings.gradle`:
```
include ':react-native-snackbar'
project(':react-native-snackbar').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-snackbar/android')
```

In `android/app/build.gradle`:

```
dependencies {
...
    compile project(':react-native-snackbar')
...
}
```
In `MainApplication.java`:

```
import com.azendoo.reactnativesnackbar.SnackbarPackage;  // <- add this

@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new SnackbarPackage(), // <- add this
      );
    }
```

**Comment by iRoachie** [comment]
@Jazz747 Made a video showing you how!  https://www.useloom.com/share/3f9227d502a54ff3b049e8b2d5fc1327

**Comment by Jazz747** [comment]
Wow man, my own personal instructional video :D I thought I had to git pull the entire project, make changes there and push. This is totally easy :) appreciate the effort, doing it now ;)

**Comment by haseebnaseem** [comment]
I am having the same problem on iOS. Any help ?

**Comment by cooperka** [comment]
@haseebnaseem have you tried the solutions suggested above? There are several things which could be wrong, usually fixed by cleaning all your caches and starting fresh.

**Comment by haseebnaseem** [comment]
@cooperka yes I have tried. Nothing works.

**Comment by cooperka** [comment]
@haseebnaseem Are you able to install and run the example app?

**Comment by haseebnaseem** [comment]
@cooperka `fatal error: 'React/RCTBridgeModule.h' file not found` when trying to build the example app.

**Comment by cooperka** [comment]
Hmm, is it possible you have some custom configuration on your machine? Do other projects work for you? Make sure you've run `yarn cache clean` before `yarn install`. I'm not really sure what could be going on for you, sorry :confused:

**Comment by davidbilik** [comment]
I had the same problem on iOS, I ran the `react-native link` command that said everything is correctly linked, but the truth was that nothing was linked :D I had to do manual linking as described here https://facebook.github.io/react-native/docs/linking-libraries-ios.html and then its working beautifully

**Comment by egemon** [comment]
@cooperka meet the same issue. Please add reference to the bottom of the readme in the top. Updating gradle helped me, but I first read all these threads about this error, before finding real solution at the bottom of readme.

**Comment by cooperka** [comment]
Note that this is currently documented on the [README here](https://github.com/cooperka/react-native-snackbar#undefined-import), please refer all comments to #43. I'm going to lock this issue in order to unify the conversation there. Thanks!
