### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by waqas19921** [cooperka/react-native-snackbar#3]
Saying cannot read property show of undefined

**Comment by aiserg** [comment]
For iOS:
1. `npm <thispackagename> --save`
2. `npm install rnpm -g`
3. `rnpm link <packagename>`
4. `react-native run-ios`

Works for me

**Comment by Liroo** [comment]
This package has not been updated for a long time because we do not use anymore. We have our own snackbar js Version 🎉

**Comment by aiserg** [comment]
@Liroo Will you put it in open source? =)

**Comment by Liroo** [comment]
@aiserg Complicated to do, used with redux and not an overlay, juste an view over our own navigator at root.. Later I'm gonna look at the open source solution ;)

**Comment by cooperka** [comment]
Hi @waqas19921, please try again. I've published several fixes to npm (via my [fork](https://github.com/cooperka/react-native-snackbar)). Both android and iOS should be working now!
