### ISSUE TITLE
Programatic title string? "undefined is not an object (evaluating this.state)

### ISSUE THREAD

**Issue by Jazz747** [cooperka/react-native-snackbar#32]
When trying to set string in state as the title (`this.state.string: 'Hello'`), I'm getting the aforementioned error. Is this something not supported or the issue is on my side?

I'm setting it as: 

```javascript
Snackbar.show({
    title: this.state.string,
    duration: Snackbar.LONG,
})
```

**Comment by iRoachie** [comment]
This is an error on your side @Jazz747 . This error happens when you're try to assess this.state but it's being called from another closure

**Comment by cooperka** [comment]
Were you able to resolve this @Jazz747? Please let us know if you're still having issues.
