### ISSUE TITLE
Error when try to import react-native-snackbar

### ISSUE THREAD

**Issue by sandropoluan** [cooperka/react-native-snackbar#34]
"undefined is not an object (evaluating '_reactNative.NativeModules.RNSnackbar.LENGTH_LONG')"

on React Native 0.44.0

**Comment by sandropoluan** [comment]
I think the problem because I forgot running the "react-native link react-native-snackbar"

But after running it, I got another error when try to "run-android"

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-snackbar:prepareComAndroidSupportAppcompatV72510Library'.
> Could not expand ZIP 'C:\Users\Ando\AppData\Local\Android\sdk\extras\android\m2repository\com\android\support\appcompat-v7\25.1.0\appcompat-v7-25.1.0.aar'.

**Comment by sandropoluan** [comment]
fixed after upgrading buildToolsVersion to "25.0.3"

**Comment by cooperka** [comment]
Glad you solved it :) please let me know if you need any more help.
