### ISSUE TITLE
PodSpec file not found

### ISSUE THREAD

**Issue by bkvirendra** [cooperka/react-native-snackbar#36]
Installed the latest version of the react-native-snackbar lib, then I added the pod specific code in the Podfile: `pod 'RNSnackbar', :path =>'../node_modules/react-native-snackbar'`

On executing the `pod install` command I'm getting the following error: 

```
Fetching podspec for `RNSnackbar` from `../node_modules/react-native-snackbar
[!] No podspec found for `RNSnackbar` in `../node_modules/react-native-snackbar
```

After looking into the package dir itself, I found that the pod specific file was not created on `npm install`. I installed the lib using npm itself, not sure if I missed something.

**Comment by cooperka** [comment]
Fixed in v0.3.8, thanks for letting me know @bkvirendra!
