### ISSUE TITLE
Accept style object as prop

### ISSUE THREAD

**Issue by ryancoughlin** [cooperka/react-native-snackbar#38]
You don't currently support sending a style as a prop to Snackbar do you?

**Comment by ryancoughlin** [comment]
Seeing this now:

>See Google's Material Design guidelines for more info on Snackbars and when to use them.

Ah ha, assuming you'll want to stick to those guidelines and not stray into custom fonts.

**Comment by cooperka** [comment]
I'd consider it if you submit a PR :) But eventually I'd like to go pure JS rather than native, in which case styling will be much easier to support.

**Comment by alizera** [comment]
No one is taking care of it?
