### ISSUE TITLE
[Android] Compability with React Native 0.47

### ISSUE THREAD

**Issue by sywka** [cooperka/react-native-snackbar#39]
See: [facebook/react-native@ce6fb33](https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8)

**Comment by cooperka** [comment]
Hi @sywka, would you mind updating [`SnackbarPackage`](https://github.com/cooperka/react-native-snackbar/blob/master/android/src/main/java/com/azendoo/reactnativesnackbar/SnackbarPackage.java) to fix this? I'm quite busy this week but I'd happily review a PR.

**Comment by cooperka** [comment]
Published in [v0.4.1](https://github.com/cooperka/react-native-snackbar/releases/tag/v0.4.1). Thanks!
