### ISSUE TITLE
Cannot read property 'LENGTH_LONG' of undefined

### ISSUE THREAD

**Issue by gokul-kulkarni** [cooperka/react-native-snackbar#43]
When I try to include and run I get the following error,

![screen shot 2017-08-18 at 12 24 20 pm](https://user-images.githubusercontent.com/6063899/29447616-537e53ee-8410-11e7-9623-77607768d83d.png)

**Comment by cooperka** [comment]
Hi @gokulkulkarni1987, this means that the Snackbar object itself is undefined. Please make sure you've run `react-native link react-native-snackbar` successfully, then rebuild your app using `react-native run-ios` or `react-native run-android`.

**Comment by gokul-kulkarni** [comment]
@cooperka I am very new to React Native, so I do not know when `react-native link react-native-snackbar` will be successful.

I ran `react-native link react-native-snackbar` and also tried this [link](https://github.com/cooperka/react-native-snackbar/wiki/Manual-Installation) But still it did not work.

**Comment by cooperka** [comment]
Could you try running the [example app](https://github.com/cooperka/react-native-snackbar/tree/master/example) and see if you spot any differences?

Here's my successful output for `react-native link`:

```
%> react-native link react-native-snackbar
Scanning 552 folders for symlinks in /home/react-native-snackbar/example/node_modules (2ms)
rnpm-install info Android module react-native-snackbar is already linked 
rnpm-install info iOS module react-native-snackbar is already linked 
```

**Comment by gokul-kulkarni** [comment]
The example does work, I check my config with the config in this example and keep you posted.

**Comment by gokul-kulkarni** [comment]
hi @cooperka thanks it worked. I had issue with react-native version, after updating to latest version it did work. Thanks for your support.

**Comment by mattferrin** [comment]
Same problem using react-native 0.48.3 version and react-native-snackbar 0.4.1 version. Not sure how to resolve it as of yet...

**Comment by cooperka** [comment]
Hi @mattferrin, this error generally means the library wasn't linked properly or React Native can't find it. Can you please clear all your caches and try once more? Often something small gets in the way and the only solution is starting over.

**Comment by gokul-kulkarni** [comment]
Hi @cooperka I have upgraded my react-native version to 0.49.3 and I have started the getting the issue yet again. :( 

Please find below the output of link,

```
sudo react-native link react-native-snackbar
rnpm-install info Android module react-native-snackbar is already linked 
rnpm-install info iOS module react-native-snackbar is already linked 
```

> react-native: 0.49.3
> react-native-snackbar: 0.4.2

please help me out.

**Comment by cooperka** [comment]
Hmm, I upgraded the example app to RN v0.49 and it all still seems to be working for me.

It's likely still a cache issue; try cleaning everything, including Xcode derived data, watchman, and the React Packager. I run into these sorts of issues occasionally, most often because Xcode is storing all sorts of derived data in various places. You can search online for ways of cleaning it up (unfortunately it's not as simple as just running **Clean** or deleting your project).

**Comment by mattferrin** [comment]
Tried everything, didn't work. But it works in fresh new project. Another one of those instances where the only fix is to create new project and then copy over, install, and link everything from scratch... Not the first time; not the last time.

**Comment by nclsjstnn** [comment]
i'm having this issue when i'm running the tests. i've done everything but nothing seems to work.
i'm on the last version of react-native (v0.50)

pls help

**Comment by mattferrin** [comment]
By the way, I created a new project and copied everything over, installed, and linked everything from scratch. It didn't work :) haha.

**Comment by alainib** [comment]
i got this error on IOS only 

"react": "^16.2.0",
"react-native": "^0.52.0"

I linked the package 

      $react-native link react-native-snackbar
      Scanning folders for symlinks in ........../node_modules (31ms)
      rnpm-install info Android module react-native-snackbar is already linked 
      rnpm-install info iOS module react-native-snackbar is already linked 

If i `import Snackbar from 'react-native-snackbar';`    i get the same error 

     Cannot read property 'LENGTH_LONG' of undefined

**Comment by cooperka** [comment]
Hmm, it looks like linking must have failed somehow even though it says it worked. This seems to happen to some people; try the manual linking solution here: https://github.com/cooperka/react-native-snackbar/issues/29#issuecomment-361095452

**Comment by alainib** [comment]
thanks @cooperka manually link remove the error ( https://facebook.github.io/react-native/docs/linking-libraries-ios.html )

**Comment by emersonmoura** [comment]
![image](https://user-images.githubusercontent.com/5419868/37616961-52262efe-2b90-11e8-9e03-dab958e75282.png)
In Android the same error...
I did everything that is described here and in the documentation, but the error continues

 "react-native": "0.51.0"
"react-native-snackbar": "^0.4.6",

![image](https://user-images.githubusercontent.com/5419868/37617065-b3afcfcc-2b90-11e8-83f5-0b5aa66f76e4.png)

![image](https://user-images.githubusercontent.com/5419868/37617675-8ecc1682-2b92-11e8-9f0b-123ae7f41f31.png)

**Comment by cooperka** [comment]
Hi @emersonmoura, have you tried manually linking?

**Comment by emersonmoura** [comment]
Hi @cooperka,
Yes...
I checked each file and the "link" was correct

Any hints of the exact reason? This way I can investigate better.

**Comment by cooperka** [comment]
Hmm, it's strange that it says "unmet peer dependency react-native@0.51.0" in your second screenshot. This lib requires `>=0.40` so it's definitely satisfied.

Have you tried installing with Yarn instead of npm?

**Comment by emersonmoura** [comment]
I also found it strange...

Yes, I tried with Yarn. Result: Same red screen

**Comment by emersonmoura** [comment]
![image](https://user-images.githubusercontent.com/5419868/37630838-6f72a016-2bc5-11e8-81dc-ab5f27c51881.png)

**Comment by cooperka** [comment]
As a last resort, you could try starting with the official [example app](https://github.com/cooperka/react-native-snackbar/tree/master/example) and progressively make it similar to your own app and see where it breaks.

**Comment by emersonmoura** [comment]
![image](https://user-images.githubusercontent.com/5419868/37670552-5c8ed504-2c48-11e8-9f94-04ac2b982005.png)

Tried starting with the official example...

Is there a problem with my machine? I use the "elementary Os"

**Comment by cooperka** [comment]
It could very well be related to your OS. If the example app doesn't work, something larger is likely wrong. Please post back if you find a solution!

**Comment by andyngdz** [comment]
If you are using Pods. Go to ios folder then pod install. 
![screen shot 2018-05-11 at 9 20 38 pm](https://user-images.githubusercontent.com/10527554/39929043-3576b7e2-5561-11e8-971a-05177350b48e.png)

**Comment by ntwigs** [comment]
I had this issue on **Android** and did the following to solve it:
- Linked the Snackbar `react-native link react-native-snackbar`
 - Changed the **distributionUrl** in the file `android/gradle/wrapper/gradle-wrapper.properties` into:      
    - `https\://services.gradle.org/distributions/gradle-4.4-all.zip`
- Changed the **buildscript dependency** in the file `android/build.gradle` into:
    - `classpath 'com.android.tools.build:gradle:3.1.3`
- Executed `react-native run-android` and voila - it worked! :tada:

**Comment by ghost** [comment]
I got the same issue on **iOS**. I already linked it manually
(https://facebook.github.io/react-native/docs/linking-libraries-ios.html).
But still got the error.
<img width="398" alt="screen shot 2018-08-19 at 10 00 54 pm" src="https://user-images.githubusercontent.com/5009491/44310169-e7731d80-a3fb-11e8-872e-5dc6864be25f.png">

**Comment by efstathiosntonas** [comment]
@itanhduy If you are using Pods. Go to ios folder then pod install.

^^ this should definitely go into README. Thanks for pointing out.

**Comment by cooperka** [comment]
The manual installation guide is [here](https://github.com/cooperka/react-native-snackbar/wiki/Manual-Installation), linked from the README. Feel free to edit the wiki if it needs improvement! Thanks.

**Comment by onmyway133** [comment]
After adding RNSnackBar.xcproj to Xcode (I recommend doing that manually instead of pod install), go to your app target -> Build Phrases -> Link Binary with Libraries and select RNSnackBar.a

**Comment by masterkrang** [comment]
woah, this bug is a nightmare, these devs should apologize. tried a lot of stuff, but no thanks, abort mission!

**Comment by juliobguedes** [comment]
@masterkrang I spent the last day trying to add this component to my app and couldnt do it. Today I decided to try once more and was able to add it (my app is ios only). Those were my steps:

1. Add `pod 'React', :path => '../node_modules/react-native'` to the beginning of my Podfile
2. `npm i --save react-native-snackbar`
3. `react-native link react-native-snackbar`
4. (Obviously optional) Fixed wrong indentation in my podfile (happened during link)
5. `cd ios/ && pod install`
6. Tried to `react-native run-ios` -> failed
7. Tried to build using Xcode -> failed: `'folly/Portability.h' file not found`
8. Added these lines at the end of my Podfile:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end
```

And it worked. Can you try these steps?

**Comment by thepday12** [comment]
You can try on Android 

- Step 1: run **react-native link react-native-snackbar**
- Step 2: open MainApplication in **getPackages** add **new SnackbarPackage()** to List
```
import com.azendoo.reactnativesnackbar.SnackbarPackage;

public class MainApplication extends NavigationApplication {

protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList( new SnackbarPackage());
   }
}
```

**Comment by janoist1** [comment]
+1

**Comment by janoist1** [comment]
Ok, it turns out that for me the issue was due to not restarting the simulator. :-)

**Comment by dpisarevskiy** [comment]
hello! this solution don't work with expo..

**Comment by bravadomizzou** [comment]
Readme says this library doesn't support expo.... hopefully will soon?

**Comment by cooperka** [comment]
Hi @bravadomizzou, it's not that Snackbar doesn't support Expo, it's the opposite -- Expo doesn't support Snackbar. You can [eject](https://docs.expo.io/versions/latest/expokit/eject/) if you want to use Snackbar, or ask Expo to build it into their set of available native components.

**Comment by ImAbhishekTomar** [comment]
I am facing the same issue.

**Comment by simonheavenvolvo** [comment]
Getting the same error but in react-native-web only.

**Comment by Rushabhgedam** [comment]
manual linking also needs to be documented for iOS in readme,
I did pod install by adding this one `pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar/RNSnackbar.podspec'`
works like charm for me

**Comment by NishitTibicle** [comment]
I am facing the same issue in ANDROID os

Its working fine in IOS

**Comment by smitkaswala** [comment]
Working well with Expo. :)

Snackbar.show({
text: 'Image Downloaded Successfully.',
duration: Snackbar.LENGTH_LONG ---> replace with static duration - '1000',
});

**Comment by alkanoidev** [comment]
@smitkaswala is there anything else i have to do?

**Comment by antonkoetzler** [comment]
> @smitkaswala is there anything else i have to do?

Use another package lmfao

**Comment by rajarajan-dev** [comment]
> Working well with Expo. :)
> 
> Snackbar.show({ text: 'Image Downloaded Successfully.', duration: Snackbar.LENGTH_LONG ---> replace with static duration - '1000', });

it fixed my issue with Expo
