### ISSUE TITLE
Set Line Height when title is of 2 Lines

### ISSUE THREAD

**Issue by GarimaMathur07** [cooperka/react-native-snackbar#46]
@cooperka How to give space between 2 lines when title is having one line above text.

Can we set Line Height between text 'Great' and Second Line 'Hello, world...'.
![device-2017-10-04-104608](https://user-images.githubusercontent.com/7220882/31160931-b061261c-a8f1-11e7-9d15-8e69893ef970.png)

**Comment by cooperka** [comment]
Hi @GarimaMathur07, currently this isn't possible but I'd love to support this. It may be easier once this library moves to pure JS instead of native code. Feel free to submit a PR in the meantime!
