### ISSUE TITLE
'React/RCTBridgeModule.h' file not found while building

### ISSUE THREAD

**Issue by wulfy** [cooperka/react-native-snackbar#49]
Hello,

I'm trying to run my app with react-native-snackbar' (react-native run-ios) and got this error (during building phase):
```
fatal error: 'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.



** BUILD FAILED **
```

I'm using react-native 0.48 and snackbar 0.4.2.
I followed installation instruction (yarn add and react-native link which successfully ended)
My application succeed to build without snackbar module.

What am I doing wrong? :x 

tx !

**Comment by cooperka** [comment]
Hmm, errors like this happen sometimes with React Native. It's likely not caused by this library itself, but more likely due to files being recompiled by Xcode. I suggest trying to clean everything and building again from scratch. Let me know if the problem persists!

**Comment by wulfy** [comment]
thank you for your answer @cooperka .
I deleted all the project and clone + build a fresh project from scratch.

I keep having the same error message :(
I will check with the rest of the team if someone did something custom with pods configuration which can lead to a problem like this ...

I managed to build the project only one time by doing "react-native upgrade" which reset some files like Xcode.
Build succeed but when I launched the project, react didn't know "firebase class" (our database).

Maybe there is a conflict with some custom configs ...

**Comment by cooperka** [comment]
You could try checking out an earlier version of your codebase, e.g. from a week ago when you know it did compile successfully. Then try installing `react-native-snackbar` onto that version.

If it works, you can use a tool like [`git bisect`](https://git-scm.com/docs/git-bisect) to figure out when things broke.

**Comment by wulfy** [comment]
@cooperka I finally found my mistake.
I'm a dumb, sorry :(
I forgot that we switch to cocoa pods to install new libs in our projects and I forgot that I should rebuild all pods when adding one (not just doing pod install after adding a lib).

Everything is working now, thank you and again for your advices + sorry for the fake issue :(

**Comment by cooperka** [comment]
No worries @wulfy, glad you found the solution :+1:
