### ISSUE TITLE
Support for windows mobile platform?

### ISSUE THREAD

**Issue by ravirupareliya** [cooperka/react-native-snackbar#52]
Does it support windows mobile platform? If not, does there any plan to add that support?

**Comment by cooperka** [comment]
Hi @ravirupareliya, I wasn't aware that React Native has any plans at all to support Windows Mobile. Officially it seems to only support Android and iOS. Can you send me any links related to this?

**Comment by ravirupareliya** [comment]
There is no official link related to it, but all the default control from react-native is giving support in windows mobile platform. Still i am not sure how far will i go with this, but i have to give support for windows mobile platform also with react-native.

**Comment by cooperka** [comment]
My recommendation would be to ignore Windows Mobile; according to recent data they only make up [0.3% of the market share](https://www.theverge.com/2017/2/16/14634656/android-ios-market-share-blackberry-2016) and it's getting smaller every year.

If you have an easy way to add support I'd consider accepting a PR, but I'm going to close this issue for now. Cheers!
