### ISSUE TITLE
Error while building for Android

### ISSUE THREAD

**Issue by rizwanahmed19** [cooperka/react-native-snackbar#55]
This is the error I'm getting when I run `react-native run-android`
```
D:\Rizwan\RN\BBXAPP\android\app\src\main\java\com\bbxapp\MainApplication.java:6: error: package com.azendoo.reactnativesnackbar does not exist
import com.azendoo.reactnativesnackbar.SnackbarPackage;
                                      ^
D:\Rizwan\RN\BBXAPP\android\app\src\main\java\com\bbxapp\MainApplication.java:37: error: cannot find symbol
            new SnackbarPackage(),
                ^
  symbol: class SnackbarPackage
2 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by cooperka** [comment]
Hi @rizwanahmed19, make sure you've run `react-native link` successfully and then try cleaning all caches. If that doesn't work, try out the included [example app](https://github.com/cooperka/react-native-snackbar/tree/master/example) and see if that works on your machine. Let me know if you get it working!

**Comment by rizwanahmed19** [comment]
The problem is that `react-native link` is not working properly, it's skipping the part where it has to add 
```
dependencies {
    ...
    compile project(':react-native-snackbar')
}
```
to `android/app/build.gradle`. So I manually added the above code to build.gradle and it worked fine
