### ISSUE TITLE
Native on Android and JS on ios?

### ISSUE THREAD

**Issue by Noitidart** [cooperka/react-native-snackbar#56]
Hi there I was trying to learn about this module. Does it use a native snack bar component (is there one?) on Andoid? And if iOS it does a js polyfill?

Thanks for this superb module.

**Comment by cooperka** [comment]
Hi @Noitidart, welcome and thank you for the kind words! Yes, it uses the native Snackbar component on Android, and it uses a custom native view on iOS (in order to appear on top of your app without adding an explicit React component for it). Let me know if you have any other questions.

**Comment by Noitidart** [comment]
Thank you sir! This is superb news!! I love native modules! Thanks also for remembering me from your other modules haha. You make some awesome stuff I am tryign to learn native modules and will hopefully join your ranks. :) Im not a java or objc/swift guy but I think i can do this, I hope I can, I really really enjoy native modules.

**Comment by cooperka** [comment]
Java and objc/swift are all very learnable languages! Happy coding and maybe you'll be making some nice PRs here someday soon ;)
