### ISSUE TITLE
Snackbar text black on older devices

### ISSUE THREAD

**Issue by iRoachie** [cooperka/react-native-snackbar#6]
The text for the Snackbar appears black on devices using android 4.4. 

![screen shot 2016-12-08 at 9 18 45 pm](https://cloud.githubusercontent.com/assets/5962998/21034174/0058816c-bd8c-11e6-88e8-7f1bfdcbea3c.jpg)

Currently making this change to SnackbarModule.java to display it correctly.
```java
Snackbar snackbar = Snackbar.make(view, Html.fromHtml("<font color=\"#ffffff\">" + title + "</font>"), duration);

```

**Comment by cooperka** [comment]
Thanks for the report @iRoachie! If you're using Snackbar on pre-Lollipop devices you'll probably need to compile the design support library as suggested [here](http://android-developers.blogspot.com.es/2015/05/android-design-support-library.html). I'll label this as an "enhancement request" so we can add documentation. Please let me know if this works for you:

```gradle
 compile 'com.android.support:design:22.2.0'
```

**Comment by iRoachie** [comment]
@cooperka Where do I add this? `android/app/build.gradle` ? All the examples show it for that file. But I'm not seeing any changes after adding it. The text still shows black

**Comment by cooperka** [comment]
@iRoachie yes, `android/app/build.gradle` under `dependencies`. You should see several other `compile` statements written there already, just add this one as well.

**Comment by iRoachie** [comment]
@cooperka It didn't change anything for me.

**Comment by cooperka** [comment]
Hmm, you're right, and it's actually defined [here](https://github.com/cooperka/react-native-snackbar/blob/master/android/build.gradle#L25) in this library already. I'll have to look into this more. I'll give you an update here if I find anything -- hopefully your workaround works well enough for you until then.

**Comment by iRoachie** [comment]
What we could do I guess is provide a colour property to the show method so users can show any colour they want.

**Comment by iRoachie** [comment]
@cooperka Decided yet?

**Comment by cooperka** [comment]
@iRoachie if you submit a PR I'll happily review it :) This doesn't seem to be a heavily requested feature at the moment, so I've been focusing on a few other things first. I think the main thing that should be done is to fix the weird default color on older devices, but if you want to support changing the text color explicitly I think that's a good feature to add too.

**Comment by iRoachie** [comment]
Alright will work on it! Thanks
