### ISSUE TITLE
react-native-snackbar error while updating react-native

### ISSUE THREAD

**Issue by shubhnik** [cooperka/react-native-snackbar#60]
I ran `react-native-git-upgrade` and this error occurs:
![screen shot 2018-01-27 at 12 42 37 pm](https://user-images.githubusercontent.com/9150371/35469686-bbd628ac-0360-11e8-82f5-af2e95b215a1.png)

Anyone had encountered this error?

**Comment by cooperka** [comment]
Hi @shubhnik, I've seen this before with other libraries, and resolved it using `yarn cache clean` then trying again. I'm not sure what causes it, something with the Yarn cache or registry. Let me know if that works for you!
