### ISSUE TITLE
PaddingBottom on iPhone X

### ISSUE THREAD

**Issue by uragecz** [cooperka/react-native-snackbar#61]
There should be paddingBottom on iPhone X ...
<img width="353" alt="screen shot 2018-01-30 at 13 03 41" src="https://user-images.githubusercontent.com/15018124/35565490-0805d696-05be-11e8-8be0-51ee6588ac99.png">

**Comment by cooperka** [comment]
Thanks for the report @uragecz. Do you mind submitting a PR?
