### ISSUE TITLE
Crash when repeatedly tapping the action button

### ISSUE THREAD

**Issue by gregoiredumas** [cooperka/react-native-snackbar#63]
> E/AndroidRuntime: FATAL EXCEPTION: main
>                                                    Process: com.XXXXX, PID: 16540
>                                                    java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
>                                                        at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:30)
>                                                        at com.azendoo.reactnativesnackbar.SnackbarModule$1.onClick(SnackbarModule.java:103)
>                                                        at android.support.design.widget.Snackbar$1.onClick(Snackbar.java:250)
>                                                        at android.view.View.performClick(View.java:5198)
>                                                        at android.view.View$PerformClick.run(View.java:21147)
>                                                        at android.os.Handler.handleCallback(Handler.java:739)
>                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                        at android.os.Looper.loop(Looper.java:148)
>                                                        at android.app.ActivityThread.main(ActivityThread.java:5417)
>                                                        at java.lang.reflect.Method.invoke(Native Method)
>                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by cooperka** [comment]
Interesting. Generally, the action button will cause the snackbar to be dismissed; does this require tapping it repeatedly before it goes offscreen?

**Comment by gregoiredumas** [comment]
It does get dismissed on first tap, as expected. But if you tap twice or more before it goes offscreen than that will cause a crash.

**Comment by cooperka** [comment]
Thank you for the report @gregoiredumas. I likely won't have time to fix this but I welcome PRs.

**Comment by gregoiredumas** [comment]
@cooperka this should fix it #64 
Inspired from: https://github.com/JonasWho/react-native-kontaktio/commit/a6962edfb5f9ff08f087ceb5074aa4f81203c652
