### ISSUE TITLE
Support for multiple snackbars (cascading)

### ISSUE THREAD

**Issue by TimTruston** [cooperka/react-native-snackbar#69]
Is it possible to modify this library such that new snacks are inserted below the previous ones (if the previous ones have not timed out). Similar to how react native displays errors and warnings...
Would this be a feature you would be willing to incorporate?

**Comment by cooperka** [comment]
Hi @TechyTimo, unfortunately this would not be possible. This lib uses the native Android [Snackbar](https://developer.android.com/reference/android/support/design/widget/Snackbar.html) which has specific [design guidelines](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-usage) recommending against this behavior. It's recommended that multiple Snackbars should queue up and wait to be displayed (so as not to overwhelm the user).

If you really need this behavior, there are other libs out there that use pure-JS components and might work better for you :slightly_smiling_face: thanks for the question!

**Comment by TimTruston** [comment]
Makes sense. Thanks for sharing the link.
