### ISSUE TITLE
Android only - Possible to respect bottom bar?

### ISSUE THREAD

**Issue by Noitidart** [cooperka/react-native-snackbar#70]
Hi there,

Thanks for this module I have been absolutely loving it!!

However I had an issue please. In my Android only version, The proper way for snackbar to respect bottom bar is to show above it. Like this article here shows - https://android.jlelse.eu/scroll-your-bottom-navigation-view-away-with-10-lines-of-code-346f1ed40e9e#2514

I have installed native `CollapsibleToolbarLayout` component for Android, but am not able to figure this one. I got this native element from here - https://github.com/cesardeazevedo/react-native-collapsing-toolbar

Demos of snackbar with static bottom bar, images from the article above:

https://cdn-images-1.medium.com/max/1600/1*cTdKeZzyboy97eWor-B7ow.png

![](https://cdn-images-1.medium.com/max/1600/1*cTdKeZzyboy97eWor-B7ow.png)

Collapsing:

https://cdn-images-1.medium.com/max/1600/1*GcRVkeB7XkLGdPfllbF4Wg.gif

![](https://cdn-images-1.medium.com/max/1600/1*GcRVkeB7XkLGdPfllbF4Wg.gif)

**Comment by cooperka** [comment]
Hi @Noitidart, thanks again for the feedback! I'm going to mark this as a duplicate of https://github.com/cooperka/react-native-snackbar/issues/15. I'd love to support this eventually but it's not feasible with the current implementation.

If you really want to accomplish this, you could try pushing a transparent modal on top of the current view (with the bottom of the modal positioned at the top of the tab bar) and show the Snackbar on the transparent modal. I'm not sure if this would work; it's more of a hack than a real solution. See https://github.com/cooperka/react-native-snackbar/issues/28 for more context.

**Comment by Noitidart** [comment]
Thanks cooperka :)

This guy in this article says the right way to do it is to use `CoordinatedLayout` - https://android.jlelse.eu/scroll-your-bottom-navigation-view-away-with-10-lines-of-code-346f1ed40e9e#2514

So maybe if someone can just wrap a CoordinatedLayout around it, then this module doesnt need any edits. That's what I'm thinking. I think the native snackbar automatically respects coordinated layout.

**Comment by cooperka** [comment]
It looks like that would be easy to do with a native Android app, but I don't know offhand how to get a view ID from JS into Java (`snackbarLayout.layoutParams.anchorId = child.id` in the article you linked to). I'd be very happy if someone solved this and submitted a PR!

**Comment by Noitidart** [comment]
Oh that's pretty simple.
I just learned it the other day when I was using the native android `UIManager.showPopupMenu` that is exposed in RN.

We use `findNodeHandle` on a `ref`.

    import { findNodeHandle, UIManager } from 'react-native'

I use it like this - https://github.com/Noitidart/react-native-popup-menu-android/blob/master/src/index.android.js#L15

**Comment by Noitidart** [comment]
I'm not a native guy so I can't figure out what to do with things like findNodeHandle unless I see others doing it. I'm hoping by sharing it others can figure this out and be like man this is easy haha :D
