### ISSUE TITLE
NativeModules.RNSnackbar.LENGTH_LONG - Cannot read property 'LENGTH_LONG' of undefined

### ISSUE THREAD

**Issue by Pliman** [cooperka/react-native-snackbar#74]
Hello, when I am writing a 'Hello world' example according to readme, I got this error
"Cannot read property 'LENGTH_LONG' of undefined"
I think it's because this expression: "LENGTH_LONG: NativeModules.RNSnackbar.LENGTH_LONG,", which in src/index.js

I used "expo": "^27.0.1" with react native version 0.55.2
I imported react-native-snackbar this way:
import * as SnackBar from 'react-native-snackbar', I think error occured when importing.

Can somebody help me on this?

**Comment by Pliman** [comment]
When debug app, I add
console.log(_reactNative.NativeModules.RNSnackbar)
after
var _reactNative = require('react-native');
in lib/index.js

_reactNative.NativeModules.RNSnackbar is undefined, so when to set RNSnackbar on _reactNative.NativeModules?

**Comment by Pliman** [comment]
link information:

> react-native link react-native-snackbar
Scanning folders for symlinks in /data/projects/{xxx}/node_modules (17ms)

**Comment by Grandmac** [comment]
Maybe it's because you don't re-run react-native run-ios or run-android after linking the package

**Comment by cooperka** [comment]
Hi @Pliman, this seems potentially similar to https://github.com/cooperka/react-native-snackbar/issues/43. Can you give those suggestions a try? Let me know if you're still having issues.

I'm also not sure if this will work with Expo -- I thought Expo doesn't support native libraries? I could be wrong.

**Comment by 5ervant** [comment]
**Not working with Expo.   ;(**

**Comment by romreed** [comment]
still get with error
 "react-native": "0.61.2"

**Comment by smitkaswala** [comment]
Working well with Expo. :)

 Snackbar.show({
         text: 'Image Downloaded Successfully.',
         duration: Snackbar.LENGTH_LONG ---> replace with static duration - '1000',
  });

**Comment by Waikato153** [comment]
> Working well with Expo. :)
> 
> Snackbar.show({ text: 'Image Downloaded Successfully.', duration: Snackbar.LENGTH_LONG ---> replace with static duration - '1000', });

I add this line to my file

import {Snackbar} from 'react-native-snackbar';

nothing else. then the error happens.
how to resolve this?
