### ISSUE TITLE
Warning when calling show function 

### ISSUE THREAD

**Issue by jpmoyn** [cooperka/react-native-snackbar#75]
I get a warning when I call this show function:

```
Snackbar.show({
        title: 'Thank you for your feedback. We will resolve this issue internally',
        backgroundColor: 'green',
        action: {
          title: 'Thanks',
          color: 'white',
          onPress: () => { /* Do something. */ },
        },
      })
```

The snackbar does not show, and I get this warning:

`TypeError: undefined is not a function (near '...Snackbar.show...')`

I am running from xcode, in a typescript RN app running on an iPad simulator.

Does anyone know how to fix this?

**Comment by cooperka** [comment]
Hi @jpmoyn, this seems potentially similar to https://github.com/cooperka/react-native-snackbar/issues/43. Can you give those suggestions a try? Let me know if you're still having issues.
