### ISSUE TITLE
Supposed to push up native floating action button?

### ISSUE THREAD

**Issue by Noitidart** [cooperka/react-native-snackbar#76]
On Android:

I'm using a native floating action button from here - https://github.com/adbayb/react-native-android-kit

Using position absolute, i position by FAB at bottom of screen.

When the native snackbar shows, I thought it would push the native floating action button up to accomadate. Is it possible to make it work like this?

**Comment by cooperka** [comment]
No, unfortunately Android doesn't automatically move components like that, even if they're both native. See issue https://github.com/cooperka/react-native-snackbar/issues/11 for more details.
