### ISSUE TITLE
Support for textColor & View inside Snackbar

### ISSUE THREAD

**Issue by melihcaliskan** [cooperka/react-native-snackbar#79]
Hello,
As you can see on the screenshoot, Google now uses **black text** and a **button** next to it.
Do you have a chance to add these features?
Thank you,  I’d really appreciate it.
Screenshoot : https://i.imgur.com/dvgSOMC.png

**Comment by cooperka** [comment]
Hi @melihcaliskan, you can already change the background color, but not the text color. It's being tracked by issue https://github.com/cooperka/react-native-snackbar/issues/47. Thanks!
