### ISSUE TITLE
Add method to dismiss indefinite snackbar

### ISSUE THREAD

**Issue by hoolymama** [cooperka/react-native-snackbar#8]
Hi, Is it possible to destroy an indefinite Snackbar?

I planned to have a snackbar show up for speech recognition with the word "listening" and close it when I get a finished event from the speech module.

**Comment by cooperka** [comment]
This is a good suggestion, but to my knowledge it's not currently possible. Feel free to submit a PR for this! In the meantime could you try showing a second snackbar (with identical content) with `LENGTH_SHORT`? That should hide them both when it hides itself a short time later.

**Comment by samridhgupta** [comment]
Any update about the same enhancement

**Comment by cooperka** [comment]
@samridhgupta no update, but please feel free to submit a PR if you'd like this feature :) I don't have much use for it in my own app, so it's not being prioritized.

I think a good method name would be `Snackbar.dismiss()`.

**Comment by iRoachie** [comment]
A temporary workaround solution could be to present a Modal with the `transparent` prop. Show the Snackbar in that modal, then when you're done, you can dismiss the modal

**Comment by cooperka** [comment]
@iRoachie if you're going to the effort to do all that, why not just submit a real PR? 😜

**Comment by iRoachie** [comment]
Lool haha. Well I actually don't need it for any use case, so the priority isn't there 😝. Thats a suggestion for the other guys

**Comment by cooperka** [comment]
Added in https://github.com/cooperka/react-native-snackbar/pull/35.
