### ISSUE TITLE
Error :react-native-snackbar:incrementalReleaseJavaCompilationSafeguard

### ISSUE THREAD

**Issue by loverdeveloper** [cooperka/react-native-snackbar#80]
Hi guys , today i run (react-native run-android) command then i get error
:react-native-snackbar:incrementalReleaseJavaCompilationSafeguard FAILED  
What is the solution ?

**Comment by cooperka** [comment]
Hi @ikosar, looks like you figured it out yourself -- was there any particular solution, or just one of those weird things that resolves itself?

**Comment by loverdeveloper** [comment]
Hi @cooperka  , it's just one of those weird things that resolves itself!
