### ISSUE TITLE
Issues after upgrading to React-Native v0.56

### ISSUE THREAD

**Issue by nicomontanari** [cooperka/react-native-snackbar#83]
This is my error:
<img width="531" alt="schermata 2018-07-20 alle 18 02 33" src="https://user-images.githubusercontent.com/15747776/43012706-2bbcc5ee-8c47-11e8-85be-161337b7be2c.png">

There may be other issues related to the changes in v0.56.

**Comment by cooperka** [comment]
Hi @nicomontanari98, thanks for the report.

It looks like there are a lot of [breaking changes](https://github.com/facebook/react-native/releases/tag/v0.56.0) in the 0.56 release. If anyone can test and verify what changes are needed, I'm happy to verify and merge PRs. Probably an SDK bump at the least.

**Comment by russelarms** [comment]
I have snackbar running after changing lines in build.gradle to 
`implementation project(':react-native-snackbar')`
Not sure if it's the case though.

**Comment by abartolo** [comment]
@cooperka The following changes have been working for all other projects. https://github.com/luggit/react-native-config/pull/248/files/d2ce3192d1eaa0df592f1c7abbb904a2bc75e98d

I changed the build.gradle file in './node_modules/react-native-snackbar' and my build passed the error @nicomontanari98  mentioned. However, I have yet been able to test as I am seeing similar issues with other libraries I have to also fix.

**build.gradle**
```

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
    }
}

apply plugin: "com.android.library"

def _ext = rootProject.ext
def _reactNativeVersion = _ext.has('reactNative') ? _ext.reactNative : '+'
def _compileSdkVersion = _ext.has('compileSdkVersion') ? _ext.compileSdkVersion : 25
def _buildToolsVersion = _ext.has('buildToolsVersion') ? _ext.buildToolsVersion : '25.0.2'
def _minSdkVersion = _ext.has('minSdkVersion') ? _ext.minSdkVersion : 16
def _targetSdkVersion = _ext.has('targetSdkVersion') ? _ext.targetSdkVersion : 25

android {
    compileSdkVersion _compileSdkVersion
    buildToolsVersion _buildToolsVersion

    defaultConfig {
        minSdkVersion _minSdkVersion
        targetSdkVersion _targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    compile "com.facebook.react:react-native:${_reactNativeVersion}"

    compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'com.android.support:support-v4:25.1.0'
    compile 'com.android.support:design:25.1.0'
}
```

**Comment by abartolo** [comment]
@cooperka I just created a PR https://github.com/cooperka/react-native-snackbar/pull/85 on the discussed changes above.
