### ISSUE TITLE
Unable to build the application

### ISSUE THREAD

**Issue by theSupermacy** [cooperka/react-native-snackbar#87]
After manually adding the dependency (following the guidelines). I am getting error while running command react-native run-android

`
Failed to find Build Tools revision 26.1.0
`

I don't think android has Build Tools revision 26.1.0 . I have installed all the revision from 26 to 27. I have also updated my  **compileSdkVersion** to **26** and **buildToolsVersion** to **26.0.3**. Please see towards it.

**Comment by wbercx** [comment]
Just ran into this as well.

**Comment by theSupermacy** [comment]
I have given the [PR](https://github.com/cooperka/react-native-snackbar/pull/88).
