### ISSUE TITLE
Android compilation error: Execution failed for task ':app:transformClassesWithMultidexlistForDebug'

### ISSUE THREAD

**Issue by artus9033** [cooperka/react-native-snackbar#90]
Hello! I've installed the package & linked it via npm, but it didn't do the job, so I edited the build scripts manually. After that, everything starts to compile, but it fails on 

> :app:transformClassesWithMultidexlistForDebug

throwing the following error:

> com.android.build.api.transform.TransformException: Error while generating the main dex list.

I'm using node v10.11.0, react v16.3.2, react-native v0.55.3 and react-native-snackbar v0.5.2.

I'm attaching the full compilation log (obtained by running gradlew with the --scan option): https://scans.gradle.com/s/ghaephwpmy4lo

**Comment by cooperka** [comment]
Hmm, the full error suggests that `Program type already present: android.support.design.widget.CoordinatorLayout` might be the problem.

```
com.android.build.api.transform.TransformException: Error while generating the main dex list.
> Error while generating the main dex list.
  > com.android.tools.r8.errors.CompilationError: Program type already present: android.support.design.widget.CoordinatorLayout$1
    > Program type already present: android.support.design.widget.CoordinatorLayout$1
```

Is it possible you're trying to compile multiple different versions of the same support library? You might need to make sure all support libraries included by your app are consistent. But I've never seen this error before, input from others would be appreciated.

**Comment by mzafer** [comment]
Am seeing the same error. Below is the trace. I get this error only on including this project, otherwise the app builds fine.


* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)

**Comment by mzafer** [comment]
Additional information from the build logs is below and my versions are "react": "16.3.1", "react-native": "^0.55.3", "react-native-snackbar": "^0.5.3",



> Configure project :react-native-snackbar 
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (26.0.3) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.2.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

**Comment by cooperka** [comment]
Hi @mzafer, can you link to a working example app to show off this issue? I don't think I'll be able to diagnose it otherwise.

**Comment by mzafer** [comment]
Sure, will try do create one in the next few days.

**Comment by mzafer** [comment]
I was not able to recreate the issue on a sample project but managed to fix it in my main project. I had to add the below to my android/app/build.gradle to resolve the issue.

implementation 'com.android.support:design:27.1.0'

**Comment by cooperka** [comment]
Thanks for the workaround @mzafer. It may be that your main project was created with a different config than standard React Native projects these days. Glad you solved it!
