### ISSUE TITLE
React/RCTBridgeModule.h file not found

### ISSUE THREAD

**Issue by Balasnest** [cooperka/react-native-snackbar#92]
When attempting to build and run for ios, the below error is recieved. I have attempted both react-native link and manually linking the node module. The error persists
```
'React/RCTBridgeModule.h' file not found
```

**Comment by cooperka** [comment]
Hi @Balasnest, sorry you're having difficulties. Can you please link to an example app with repro steps? Unfortunately there's not much I can help with unless I have more information.

**Comment by Balasnest** [comment]
Thanks for your reply. Resolved it by removing node_modules and installing again.
